update setup

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -15,8 +15,14 @@ ln -sf "$PWD/config.nix" "$XDG_CONFIG_HOME"/nixpkgs/config.nix
 # install Nix packages from config.nix
 nix-env -iA nixpkgs.myPackages
 
-source "$HOME/.conda/bin/conda"
-conda init
-# source "$HOME/.bashrc"
+exec bash
+if [ -f "$HOME/.conda/bin/conda" ]; then
+    source "$HOME/.conda/etc/profile.d/conda.sh"
+    conda init bash
+else
+    echo "Conda not found at $HOME/.conda/bin/conda"
+    exit 1
+fi
+source "$HOME/.bashrc"
 conda create -n py311 python=3.11
 conda activate py311
